apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-products
  labels:
    app: store-products
spec:
  replicas: 4
  selector:
    matchLabels:
      app: store-products
  template:
    metadata:
      labels:
        app: store-products
    spec:
      containers:
      - name: store-products
        image: 160342149700.dkr.ecr.ap-southeast-2.amazonaws.com/api:latest
        ports:
        - containerPort: 80
